from pydantic import BaseModel, EmailStr
from typing import List, Optional
from datetime import datetime

class Country(BaseModel):
    country: str  # Country code (e.g., 'US', 'AD')
    postal_code: Optional[str] = None
    # district: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    accuracy: Optional[int] = None
    states: Optional[List[str]] = []  # List of states
    district: Optional[List[str]] = []  # List of cities

class Location(BaseModel):
    branchId: Optional[str] = None  # MongoDB ObjectId
    randomId: Optional[str] = None
    branchName: Optional[str] = None
    aliasName: Optional[str] = None
    status: Optional[str] = None  # Active / Inactive
    address: Optional[str] = None
    country: Optional[str] = None  # Country code
    state: Optional[str] = None
    city: Optional[str] = None
    postalCode: Optional[int] = None
    phoneNumber: Optional[str] = None
    email: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    description: Optional[str] = None
    openingHours: Optional[datetime] = None
    closingHours: Optional[datetime] = None
    managerName: Optional[str] = None
    managerContact: Optional[str] = None
    createdDate: Optional[datetime] = None
    lastUpdatedDate: Optional[datetime] = None
    createdBy:Optional[str]=None

class LocationPost(BaseModel):
    branchName: str
    aliasName: Optional[str] = None
    status: Optional[str] = None  # Active / Inactive
    randomId: Optional[str] = None  # Generated by backend
    address: Optional[str] = None
    country: str  # Country code (e.g., 'US', 'AD')
    state: str  # State selected from dropdown
    city: str  # City selected from dropdown
    postalCode: Optional[int] = None
    phoneNumber: Optional[str] = None
    email: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    description: Optional[str] = None
    openingHours: Optional[datetime] = None
    closingHours: Optional[datetime] = None
    managerName: Optional[str] = None
    managerContact: Optional[str] = None
    createdDate: Optional[datetime] = None
    lastUpdatedDate: Optional[datetime] = None
    createdBy:Optional[str]=None


class CityResponse(BaseModel):
    POSTAL_CODE: int  # You can use str or int based on your needs
    LATITUDE: float
    LONGITUDE: float